export const blackList = [
  'pain', 'rx', 'mg', 'tablets', 
]

const whiteList1 = ["acid", "acids", "acyclovir", "advil", "aerosphere", "albuterol", "alli diet", "allopurinol", "amoxicillin", "amoxil", "ampicillin", "antabuse", 'aqua', "arimidex", "atenolol", "augmentin", "avana", "avanafil", "avodart", "aygestin", "baclofen", "bcise", "benicar", "benralizumab", "bevespi", "brilinta", "budesonide", "bupropion", "buspar", "bydureon", "byetta", "cafergot", "calcium", "calquence", "celebrex", "celexa", "cephalexin", "chlorthalidone", "cialis", "cipro", "cleocin", "clindamycin", "clomid", "clonidine", "cyclosilicate", "cymbalta", "daliresp", "dapagliflozin", "deruxtecan-nxki", "diclofenac", "dihydrate", "durvalumab", "effexor", "elimite", "enhertu", "epanova", "esomeprazole", "exenatide", "fam-trastuzumab", "faserna", "faslodex", "flagyl", "flexhaler", "fluconazole", "flumist", "formoterol", "fourosimide", "fumarate", "fulvestrant", "gefitinib", "glycopyrrolate", "hci", "hydrochloride", "hydrochlorothiazide", "imfinzi", "inderal", "indocin", "indomethacin", "influenza", "intranasal", "iressa", 'iv', 'i.v.', "keflex", "kombiglyze", "koselugotm", "lasix", "levitra", "lexapro", "lipitor", "lisinopril", "lokelma", "lumoxiti", "lynparza", "magnesium", "medrol", "metformin", "methotrexate", "minoxidil", "motilium", "motrin", "moxetumomab", "neurontin", "nexium", "nolvadex", "olaparib", "omega-3", "omega-3-carboxylic", "onglyza", "osimertinib", "pasudotox-tdfk", "permethrin", "pramlintide", "prednisolone", "prednisone", "proscar", "provera", "prozac", "pulmicort", "qtern", "qternmet", "quadrivalent", "quetiapine", "respules", "retin-a", "rhinocort", "rimonabant", "robaxin", "roflumilast", "rogaine", "rosuvastatin", "saxagliptin", "selumitinib", "seroquel", "sodium", "strattera", "stromectol", "suhagra", "symbicort", "symlin", "synthroid", "tadacip", "tadalafil", "tagrisso", "tamoxifen", "tenormin", "ticagrelor", "toradol", "trazodone", "tretinoin", "triamterene", "vaccine", "vermox", "viagra", "vigara", "wellbutrin", "xigduo", "xr", "yasmin", "zirconium", "zithromax", "zofran", "zoloft"]

const whiteList2 = [
"ABILIFY",
"ACALABRUTINIB",
"ACETATE",
"ADVAIR DISKUS",
"AFLURIA QUAD 2019-20 (3YR UP)",
"AFLURIA QUAD 2019-20 (6-35MO)",
"AFLURIA QUAD 2019-2020",
"AFLURIA QUAD 2020-2021",
"AFLURIA QUAD 2020-21 (3YR UP)",
"AFLURIA QUAD 2020-21 (6-35MO)",
"ANORO ELLIPTA",
"BASAGLAR KWIKPEN U-100",
"BEVESPI",
"BREO ELLIPTA",
"BYSTOLIC",
"CYCLOSPORINE",
"DEXILANT",
"ELIQUIS",
"ENTRESTO",
"FARXIGA",
"FLOVENT HFA",
"FLUAD QUAD 2020-2021",
"FLUARIX QUAD 2019-2020",
"FLUARIX QUAD 2020-2021",
"FLUBLOK QUAD 2019-2020",
"FLUBLOK QUAD 2020-2021",
"FLUCELVAX QUAD 2019-2020",
"FLUCELVAX QUAD 2020-2021",
"FLUZONE HIGH-DOSE QUAD 2020-21",
"FLUZONE QUAD 2019-2020",
"FLUZONE QUAD 2020-2021",
"FLUZONE QUAD PEDI 2019-2020",
"HUMALOG KWIKPEN U-100",
"HUMALOG KWIKPEN U-200",
"HUMIRA",
"HUMIRA PEN",
"HUMIRA PEN CROHN'S-UC-HS",
"HUMIRA PEN PSOR-UVEITS-ADOL HS",
"HUMIRA(CF)",
"HUMIRA(CF) PEN",
"JANUVIA",
"JARDIANCE",
"LANTUS",
"LANTUS SOLOSTAR",
"LATUDA",
"LEVEMIR FLEXTOUCH",
"LINZESS",
"LO LOESTRIN FE",
"MYRBETRIQ",
"NOVOLOG FLEXPEN",
"OZEMPIC",
"SHINGRIX",
"SILDENAFIL",
"SIMVASTATIN",
"SPIRIVA",
"SYNTHROID",
"SYMBICORT",
"SUBOXONE",
"TACROLIMUS",
"TRADJENTA",
"TRELEGY ELLIPTA",
"TRESIBA",
"TRESIBA FLEXTOUCH U-100",
"TRESIBA FLEXTOUCH U-200",
"TRULICITY",
"VASCEPA",
"VENTOLIN HFA",
"VYVANSE",
"XARELTO",
"HUMALOG",
"VICTOZA 2-PAK",
"VICTOZA 3-PAK",
"CHANTIX",
"TRINTELLIX",
"DILUTING MEDIUM FOR NOVOLOG",
"NOVOLOG",
"SPIRIVA RESPIMAT",
"BRILINTA",
"LUMIGAN",
"INCRUSE ELLIPTA",
"JANUMET",
"BIKTARVY",
"PNEUMOVAX 23",
"COMBIGAN",
"VIMPAT",
"OXYCONTIN",
"INVOKANA",
"AIMOVIG AUTOINJECTOR",
"BOOSTRIX TDAP",
"COMBIVENT RESPIMAT",
"TOUJEO SOLOSTAR",
"VIIBRYD",
"ADVAIR HFA",
"PREVNAR 13",
"DULERA",
"DESCOVY",
"ENBREL",
"ENBREL MINI",
"ENBREL SURECLICK",
"VRAYLAR",
"EMGALITY PEN",
"EMGALITY SYRINGE",
"EMGALITY SYRINGE",
"JANUMET XR",
"PREMARIN",
"DUPIXENT PEN",
"DUPIXENT SYRINGE",
"NARCAN",
"INVEGA SUSTENNA",
"TRUVADA",
"LEVEMIR",
"AMITIZA",
"REPATHA SURECLICK",
"PREMARIN",
"REXULTI",
"XIFAXAN",
"XIIDRA",
"GENVOYA",
"ALPHAGAN P",
"PRADAXA",
"ARNUITY ELLIPTA",
"FOCALIN XR",
"STIOLTO RESPIMAT",
"NUVARING",
"OTEZLA",
"TIVICAY",
"TIVICAY PD",
"LIVALO",
"TRIUMEQ",
"NOVOLOG MIX 70-30 FLEXPEN",
"XIGDUO XR",
"HUMULIN R U-500",
"EPIDUO FORTE",
"PULMICORT FLEXHALER",
"BYDUREON PEN",
"ATROVENT HFA",
"DUREZOL",
"LOTEMAX",
"LOTEMAX SM",
"NEXIUM",
"DALIRESP",
"TOVIAZ",
"MULTAQ",
"BELSOMRA",
"TRAVATAN Z",
"LYRICA",
"XOLAIR",
"HUMALOG MIX 75-25 KWIKPEN",
"CREON",
"AZOPT",
"SIMBRINZA",
"PREMPRO",
"NAMZARIC",
"MOVANTIK",
"CONTRAVE",
"NUEDEXTA",
"TECFIDERA",
"PROVENTIL HFA",
"FLOVENT DISKUS",
"PFIZER COVID-19 VACCINE (EUA)",
"PROLIA",
"ONGLYZA",
"JUBLIA",
"DILANTIN",
"TOPROL XL",
"FLUAD 2019-2020",
"FLUAD 2020-2021",
"ASMANEX",
"BROVANA",
"FLUZONE HIGH-DOSE 2019-2020",
"NUCYNTA",
"ADACEL TDAP",
"COPAXONE",
"RISPERDAL CONSTA",
"RENVELA",
"SAPHRIS",
"PREMPRO",
"CRESTOR",
"ISENTRESS",
"ISENTRESS HD",
"SAVELLA",
"PREZISTA",
"JENTADUETO",
"BESIVANCE",
"DYMISTA",
"NOVOLOG MIX 70-30",
"ILEVRO",
"CARAFATE",
"VIAGRA",
"INVOKAMET",
"LIPITOR",
"KOMBIGLYZE XR",
"WELCHOL",
"MODERNA COVID-19 VACCINE (EUA)",
"ATRIPLA",
"COUMADIN",
"CIALIS",
"XOPENEX HFA",
"TAMIFLU",
"VESICARE",
"BENICAR",
"EXELON",
"PRISTIQ",
"ULORIC",
"RANEXA",
"BENICAR HCT",
"SENSIPAR",
"RELPAX",
"STRATTERA",
"NORVIR",
"ZETIA",
"SEROQUEL XR",
"NASONEX",
"VIREAD",
"LEVITRA",
"RAPAFLO",
"VYTORIN",
"VOLTAREN",
"MINASTRIN 24 FE",
"AZOR",
"PATADAY",
"TRANSDERM-SCOP",
"NAMENDA XR",
"EFFIENT",
"NAMENDA",
"EPIDUO",
"ZOSTAVAX",
]

// eventually combine whitelist 1 and 2 but for now...
const merged = whiteList1.concat(whiteList2)

merged.forEach((item, index) => {
  merged[index] = item.toLowerCase();
})

let finalList = [...new Set(merged)]

export const whiteList = [...finalList];

export const contras = [
  { name: "Simvastatin", description: "a statin to treat cholesterol" },
  {
    name: "Cyclosporine",
    description: "a medicine for your immune system",
  },
  {
    name: "Tacrolimus",
    description: "a medicine for your immune system",
  },
  {
    name: "Sildenafil",
    description: "a medicine to treat erectile disfunction",
  },
  {
    name: "CYP3A Inhibitors",
    description: "such as diltiazem, itraconazole, and clarithromycin",
  },
]