export const blackList = [
  'pain', 'rx', 'mg', 'tablets', 
]

const whiteList1 = ["acid", "acids", "aerosphere", "alli diet", "ampicillin", "antabuse", 'aqua', "arimidex", "atenolol", "augmentin", "avana", "avodart", "aygestin", "benralizumab", "budesonide", "bupropion", "buspar", "cafergot", "calcium", "cephalexin", "chlorthalidone", "cipro", "cleocin", "clindamycin", "clomid", "clonidine", "cyclosilicate", "cymbalta", "daliresp", "dapagliflozin", "deruxtecan-nxki", "diclofenac", "dihydrate", "durvalumab", "effexor", "elimite", "enhertu", "epanova", "esomeprazole", "exenatide", "fam-trastuzumab", "faserna", "faslodex", "flagyl", "flexhaler", "fluconazole", "flumist", "formoterol", "fourosimide", "fumarate", "fulvestrant", "gefitinib", "glycopyrrolate", "hci", "hydrochloride", "hydrochlorothiazide", "imfinzi", "inderal", "indocin", "indomethacin", "influenza", "intranasal", "iressa", 'iv', 'i.v.', "keflex", "kombiglyze", "koselugotm", "magnesium", "medrol", "metformin", "methotrexate", "minoxidil", "motilium", "motrin", "moxetumomab", "neurontin", "nolvadex", "olaparib", "omega-3", "omega-3-carboxylic", "onglyza", "osimertinib", "pasudotox-tdfk", "permethrin", "pramlintide", "prednisolone", "prednisone", "proscar", "provera", "prozac", "pulmicort", "qtern", "qternmet", "quadrivalent", "quetiapine", "respules", "retin-a", "rhinocort", "rimonabant", "robaxin", "roflumilast", "saxagliptin", "selumitinib", "seroquel", "sodium", "strattera", "stromectol", "suhagra", "symbicort", "symlin", "synthroid", "tadacip", "tadalafil", "tagrisso", "tamoxifen", "tenormin", "ticagrelor", "toradol", "trazodone", "tretinoin", "triamterene", "vaccine", "vermox", "wellbutrin", "xigduo", "xr", "yasmin"]

const whiteList2 = [
"ABILIFY",
"ACALABRUTINIB",
"ACETATE",
"ACYCLOVIR",
"ADVAIR DISKUS",
"ADVAIR HFA",
"ADACEL TDAP",
"ADVIL",
"AFLURIA QUAD 2019-20 (3YR UP)",
"AFLURIA QUAD 2019-20 (6-35MO)",
"AFLURIA QUAD 2019-2020",
"AFLURIA QUAD 2020-2021",
"AFLURIA QUAD 2020-21 (3YR UP)",
"AFLURIA QUAD 2020-21 (6-35MO)",
"AIMOVIG AUTOINJECTOR",
"ALBUTEROL",
"ALLOPURINOL",
"AMITIZA",
"AMOXICILLIN",
"AMOXIL",
"AMLODIPINE",
"ANORO ELLIPTA",
"ALPHAGAN P",
"ARNUITY ELLIPTA",
"ASMANEX",
"ATRIPLA",
"ATROVENT HFA",
"AVANAFIL",
"AZOPT",
"AZOR",
"BACLOFEN",
"BASAGLAR KWIKPEN U-100",
"BCISE",
"BELSOMRA",
"BENICAR",
"BENICAR HCT",
"BEVESPI",
"BESIVANCE",
"BIKTARVY",
"BOOSTRIX TDAP",
"BREO ELLIPTA",
"BRILINTA",
"BROVANA",
"BYETTA",
"BYDUREON PEN",
"BYSTOLIC",
"CALQUENCE",
"CARAFATE",
"CELEBREX",
"CELEXA",
"CHANTIX",
"CIALIS",
"COMBIGAN",
"COMBIVENT RESPIMAT",
"CONTRAVE",
"COPAXONE",
"COUMADIN",
"CREON",
"CRESTOR",
"CYCLOSPORINE",
"DALIRESP",
"DESCOVY",
"DEXILANT",
"DILANTIN",
"DILUTING MEDIUM FOR NOVOLOG",
"DULERA",
"DUPIXENT PEN",
"DUPIXENT SYRINGE",
"DUREZOL",
"DYMISTA",
"EFFIENT",
"ELIQUIS",
"EMGALITY PEN",
"EMGALITY SYRINGE",
"EMGALITY SYRINGE",
"ENBREL",
"ENBREL MINI",
"ENBREL SURECLICK",
"ENTRESTO",
"EPIDUO",
"EPIDUO FORTE",
"EXELON",
"FARXIGA",
"FLOVENT DISKUS",
"FLOVENT HFA",
"FLUAD 2019-2020",
"FLUAD 2020-2021",
"FLUAD QUAD 2020-2021",
"FLUARIX QUAD 2019-2020",
"FLUARIX QUAD 2020-2021",
"FLUBLOK QUAD 2019-2020",
"FLUBLOK QUAD 2020-2021",
"FLUCELVAX QUAD 2019-2020",
"FLUCELVAX QUAD 2020-2021",
"FLUZONE HIGH-DOSE 2019-2020",
"FLUZONE HIGH-DOSE QUAD 2020-21",
"FLUZONE QUAD 2019-2020",
"FLUZONE QUAD 2020-2021",
"FLUZONE QUAD PEDI 2019-2020",
"FOCALIN XR",
"GENVOYA",
"HUMALOG",
"HUMALOG KWIKPEN U-100",
"HUMALOG KWIKPEN U-200",
"HUMALOG MIX 75-25 KWIKPEN",
"HUMIRA",
"HUMIRA PEN",
"HUMIRA PEN CROHN'S-UC-HS",
"HUMIRA PEN PSOR-UVEITS-ADOL HS",
"HUMIRA(CF)",
"HUMIRA(CF) PEN",
"HUMULIN R U-500",
"INCRUSE ELLIPTA",
"ILEVRO",
"INVEGA SUSTENNA",
"INVOKAMET",
"INVOKANA",
"ISENTRESS",
"ISENTRESS HD",
"JANUMET",
"JANUMET XR",
"JANUVIA",
"JARDIANCE",
"JENTADUETO",
"JUBLIA",
"KOMBIGLYZE XR",
"LANTUS",
"LANTUS SOLOSTAR",
"LASIX",
"LATUDA",
"LEVEMIR",
"LEVEMIR FLEXTOUCH",
"LEVITRA",
"LEXAPRO",
"LINZESS",
"LIPITOR",
"LISINOPRIL",
"LIVALO",
"LO LOESTRIN FE",
"LOKELMA",
"LOTEMAX",
"LOTEMAX SM",
"LUMIGAN",
"LUMOXITI",
"LYNPARZA",
"LYRICA",
"MINASTRIN 24 FE",
"MODERNA COVID-19 VACCINE (EUA)",
"MOVANTIK",
"MULTAQ",
"MYRBETRIQ",
"NAMENDA",
"NAMENDA XR",
"NAMZARIC",
"NARCAN",
"NASONEX",
"NEXIUM",
"NORVIR",
"NOVOLOG",
"NOVOLOG FLEXPEN",
"NOVOLOG MIX 70-30 FLEXPEN",
"NOVOLOG MIX 70-30",
"NUCYNTA",
"NUEDEXTA",
"NUVARING",
"ONGLYZA",
"OTEZLA",
'OXYBUTYNIN CHLORIDE',
"OXYCONTIN",
"OZEMPIC",
"PATADAY",
"PFIZER COVID-19 VACCINE (EUA)",
"PNEUMOVAX 23",
"POTASSIUM CHLORIDE",
"PRADAXA",
"PREMARIN",
"PREMPRO",
"PREVNAR 13",
"PREZISTA",
"PRISTIQ",
"PROLIA",
"PROVENTIL HFA",
"PULMICORT FLEXHALER",
"RANEXA",
"RAPAFLO",
"RELPAX",
"RENVELA",
"REPATHA SURECLICK",
"REXULTI",
"RISPERDAL CONSTA",
"ROSUVASTATIN",
"ROGAINE",
"SAPHRIS",
"SAVELLA",
"SENSIPAR",
"SEROQUEL XR",
"SHINGRIX",
"SILDENAFIL",
"SIMBRINZA",
"SIMVASTATIN",
"SPIRIVA",
"SPIRIVA RESPIMAT",
"STIOLTO RESPIMAT",
"STRATTERA",
"SUBOXONE",
"SYNTHROID",
"SYMBICORT",
"TACROLIMUS",
"TAMIFLU",
"TECFIDERA",
"TIVICAY",
"TIVICAY PD",
"TOPROL XL",
"TOUJEO SOLOSTAR",
"TOVIAZ",
"TRADJENTA",
"TRANSDERM-SCOP",
"TRAVATAN Z",
"TRELEGY ELLIPTA",
"TRESIBA",
"TRESIBA FLEXTOUCH U-100",
"TRESIBA FLEXTOUCH U-200",
"TRINTELLIX",
"TRIUMEQ",
"TRULICITY",
"TRUVADA",
"ULORIC",
"VASCEPA",
"VENTOLIN HFA",
"VIIBRYD",
"VIMPAT",
"XARELTO",
"XIGDUO XR",
"XIIDRA",
"XOLAIR",
"VESICARE",
"VIAGRA",
"VIGARA",
"VICTOZA 2-PAK",
"VICTOZA 3-PAK",
"VIREAD",
"VOLTAREN",
"VRAYLAR",
"VYTORIN",
"VYVANSE",
"WARFARIN",
"WELCHOL",
"XIFAXAN",
"XOPENEX HFA",
"ZETIA",
"ZIRCONIUM",
"ZOFRAN",
"ZOLOFT",
"ZOSTAVAX",
"ZITHROMAX",
]

// eventually combine whitelist 1 and 2 but for now...
const merged = whiteList1.concat(whiteList2)

merged.forEach((item, index) => {
  merged[index] = item.toLowerCase();
})

let finalList = [...new Set(merged)]

export const whiteList = [...finalList];

export const contras = [
  { 
    id: "",
    name: "Simvastatin",
    description: "a statin to treat cholesterol"
  },
  {
    id: "",
    name: "Cyclosporine",
    description: "a medicine for your immune system",
  },
  {
    id: "",
    name: "Tacrolimus",
    description: "a medicine for your immune system",
  },
  {
    id: "",
    name: "Sildenafil",
    description: "a medicine to treat erectile disfunction",
  },
]